### ISSUE TITLE
Please support pagination options in cmis:query

### ISSUE THREAD

**Issue by david-oc-miller** [mulesoft/cmis-connector#14]
The Mule CMIS connector is great stuff, saves me so much time compared to using the Chemistry API.  So I'm hoping the cmis:query operation can be extended to support pagination options (page number, number of results).  It looks like Chemistry supports it.

Thanks, 
Dave

**Comment by karthikanantha** [comment]
Pagination support has been added to the cmis:query operation in v2.1.0. Please build from the develop branch until this version is released.
