### ISSUE TITLE
ChemistryCMISFacade - Issue when using lists of non-strings

### ISSUE THREAD

**Issue by Amelsfort** [mulesoft/cmis-connector#20]
I believe I have found an issue in the ChemistryCMISFacade.java.
The method "translateInboundProperties" received a Map<String, String> and returns a Map<String, Object>, but because of the inbound map, the resulting value will always be a String! This results in an exception when trying to use a list of (for example) Integers or Dates. Even though the resulting map would work fine with those types.

**Comment by karthikanantha** [comment]
Hi Amelsfort, 
Thank you for reporting the issue. This has been fixed in the develop branch and will be available in the up coming release.

You can build the connector from develop branch until the new release is available.
