### ISSUE TITLE
Issue sending non-string

### ISSUE THREAD

**Issue by Amelsfort** [mulesoft/cmis-connector#21]
I am currently string to send a date to Alfresco, but this result in an exception on line 960 in ChemistryCMISFacade.java.
This is because the map I'm sending contains a Date-object, but the function 'translateInboundProperties' receives a Map<String, String>.

Since the function returns a Map<String, Object>, I believe it should also be able to receive one and, when the value is not a string starting with 'm:', just copy the object to the new map and return it.

**Comment by karthikanantha** [comment]
Hi Amelsfort, 

We have removed translateInboundProperties method, in-order to support Map<String, Object> instead of Map<String, String>.

If you want to test the fix, Please build the connector from the develop branch until the new version of connector is released.
