### ISSUE TITLE
Can RepositoryId be dynamically resolved ?

### ISSUE THREAD

**Issue by cortex93** [mulesoft/cmis-connector#22]
RepositoryId seems to be configurable only with a properties. It would be nice to be able to set its value with a MEL expression.
My goal is to be able to retrieve the repositoryId with help of a subflow like below

```xml

<cmis:config name="CMISRepoVar"
		baseUrl="${cmis.baseurl}/_vti_bin/cmissoapwsdl.aspx?wsdl"
		password="${cmis.password}"
		username="${cmis.login}" doc:name="CMIS" endpoint="SOAP"
		repositoryId="#[flowVars['cmisRepositoryId']]"
		/>
<flow name="Flow">
    <inbound-endpoint .../>
    <enricher target="#[flowVars['cmisRepositoryId']]" doc:name="Message Enricher">
            <processor-chain doc:name="Processor Chain">
                <!-- set the name from properties or message -->
                <set-variable doc:name="Variable" value="${cmis.repository.name}" variableName="cmisRepositoryName"/>
                <flow-ref name="cmis.getRepositoryId" doc:name="Flow Reference"/>
            </processor-chain>
    </enricher>
    <cmis:create-document-by-path config-ref="CMISRepoVar" ...>
</cmis>

</flow>
<sub-flow name="cmis.getRepositoryId">        
        <cmis:repositories config-ref="CMIS" doc:name="CMIS"/>
        <collection-splitter enableCorrelation="NEVER" doc:name="Collection Splitter"/>
        <expression-filter expression="#[payload.name == flowVars['cmisRepositoryName']]" doc:name="Expression"/>
        <expression-transformer doc:name="Expression" expression="#[payload.id]"/>
        <echo-component doc:name="Echo" />
    </sub-flow>
```

**Comment by karthikanantha** [comment]
The issue has been fixed in v2.1.0. Please build the connector from the latest develop branch until the new version v2.1.0 is available.

**Comment by cortex93** [comment]
It does not work in the given example.
cmis:repositories connect to the baseUrl and as the repositoryId expression returns empty, the first available repository is retrieved and set in the facade.
It is therefore not possible to change of repository unless you change of connection identifier (username + baseUrl)
create-document-by-path will upload the document to the first available repo and not to the expected one.

**Comment by cortex93** [comment]
Adding RepositoryId to the ConnectionKey did the trick.
