### ISSUE TITLE
InputStream is not closed after createDocument

### ISSUE THREAD

**Issue by cortex93** [mulesoft/cmis-connector#23]
When the cmis connector is placed after a File connector, the payload is an InputStream that must be closed in order to delete/move the file.
This happens only when an exception is thrown as the default exception strategy forcibly close the payload.

Inside the apache cmis implementation, the InputStream is wrapped with a decorator that prevent closing.
Thus, closing the stream seems to be the responsiblity of the cmis connector.

**Comment by karthikanantha** [comment]
The bug has been fixed in the develop branch and will be available in the upcoming v2.1.0 release  of the connector.
