### ISSUE TITLE
Add authentication provider configuration key

### ISSUE THREAD

**Issue by cortex93** [mulesoft/cmis-connector#24]
As for the cxfPortProvider, it would be nice to be able to change default authentication provider to NTLM by specify authenticationProvider="org.apache.chemistry.opencmis.client.bindings.spi.NTLMAuthenticationProvider" on the cmis:config element.

This would map to
parameters.put(SessionParameter.AUTHENTICATION_PROVIDER_CLASS, authenticationProvider);

**Comment by karthikanantha** [comment]
NTLM support in CMIS connector has been added in v2.1.0. Please build the connector from the latest.
