### ISSUE TITLE
Operations with Cmis Object Reference not working

### ISSUE THREAD

**Issue by patriciay-appno** [mulesoft/cmis-connector#45]
All the operations that has the option to input CMIS Object Reference or Object Id are not working as expected. (i.e get parents, update properties...)

Even if I put something in the object Id, it always gets the CMIS object reference as payload and this obliges me to put a get-object-by-id operation in front of these kind of operations always.

**Comment by cortex93** [comment]
Have you tried to explicitly set cmisObject to null ? If not specified, it will default to #[payload] and has higher precedence.

**Comment by patriciay-appno** [comment]
Good point, I will try that

**Comment by patriciay-appno** [comment]
setting the cmisObject to null worked. Thank you
